#!/bin/sh

while true
do
sleep 10
oc get co | awk '{ print $5 }' | grep -v -E "DEGRADED|False" || break
done

while true
do
sleep 10
oc get no | grep -v -E "STATUS|Ready" || break
done

cat <<EOF | oc apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
spec: {}
EOF

cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-management
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
EOF

cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  channel: release-2.7
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
    - key: node-role.kubernetes.io/infra
      effect: NoSchedule
      operator: Exists
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF

while true
do
sleep 10
oc get crd -A | grep open-cluster-management && break
done

cat 0<<EOF | oc apply -f -
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
EOF

while true
do
sleep 10
oc get crd -A | grep open-cluster-management && break
done

while true
do
sleep 10
oc get po -n open-cluster-management | grep -v -E "STATUS|Completed|Running" || break
done
