#!/bin/sh

while true
do
sleep 10
oc get co | awk '{ print $5 }' | grep -v -E "DEGRADED|False" || break
done

while true
do
sleep 10
oc get no | grep -v -E "STATUS|Ready" || break
done

cat <<EOF | oc apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops
spec: {}
EOF

cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF

while true
do
sleep 10
oc get crd -A | grep gitopsservices && break
done

oc patch gitopsservice/cluster --patch '{"spec":{"runOnInfra":true,"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/infra","operator":"Exists"}]}}' --type=merge

oc --namespace openshift-gitops delete secret openshift-gitops-tls && oc --namespace openshift-gitops create secret tls openshift-gitops-tls --cert=${dir}/tls/apps/fullchain.pem --key=${dir}/tls/apps/privkey.pem
oc --namespace openshift-gitops delete deploy openshift-gitops-server

while true
do
sleep 10
oc get po -n openshift-gitops | grep -v -E "STATUS|Completed|Running" || break
done
